config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tweets
  resources :hashtags

  root 												 'static_pages#dashboard'
  get			'dashboard' 			=> 'static_pages#dashboard'
  get     'maps'            => 'static_pages#maps'
  get     'engagement'      => 'static_pages#engagement'
  get     'raw_data'        => 'static_pages#raw_data'
  get     'photos'          => 'static_pages#photos'

  get 'static_pages/hashtags', :defaults => { :format => 'json' }

end

app/models/tweet.rb
class Tweet < CouchRest::Model::Base

end

app/models/user.rb
class User < CouchRest::Model::Base
	include TwitterApiHelper

	before_save :parse_user

	use_database 'users'

	property :_id, 								String
	property :username,						String
	property :tweet_count,				Integer
	property :created_at,					String
	property :description,				String
	property :lang,								String
	property :location,						String
	property :name,								String
	property :statuses_count, 		Integer
	property :time_zone,					String
	property :utc_offset,					String

	design do
		view :by_username
		view :by_created_at
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  require 'json'
  require 'uri'

	private
	  def set_db
	    couch_server = 'http://115.146.95.29:5984'
	    database = '/maydebout'
      # database = '/realdonaldtrump'
	    design_doc = '/_design/analytics'
	    @connection = couch_server+database+design_doc
	    @connection_raw = couch_server+database
	  end

    def get_tweet_html(tweet_data)
			tweets_html = []
			tweet_data.each do |tweet|
				begin
					tweet_obj = get_tweet(tweet['key'][1].to_str)
					tweets_html.push(tweet_obj)
				rescue
					print "Error on tweet id: " + tweet['key'][1] +"\n"
				end
			end
			return tweets_html
		end

    def request_data(url)
      set_db
      JSON.parse(RestClient.get(@connection+url), {accept: :json})
    end

end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  include TwitterApiHelper
  before_action :set_db, only: [:show]

  def show
    @hashtags = request_data("/_view/hashtag_count?group=true&startkey=[%22#{params[:id]}%22]&endkey=[%22#{params[:id]}%22,%7B%7D]&stale=update_after")['rows']
  end

  def index
    @hashtags = request_data("/_list/sort_by_value/hashtag_count?group=true&group_level=1&stale=ok")['rows']
  end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	include TwitterApiHelper

  before_action :set_db, only: [:engagement, :raw_data]

	def dashboard
	end

	def us_map
	end

	def photos
		@photos = request_data("/_list/sort_by_value/photo_count?group=true&stale=update_after")['rows']
	end

	def engagement
		@retweets = request_data("/_list/sort_array_by_value/retweet_count?group=true&stale=update_after")['rows']
		@retweets_html = get_tweet_html(@retweets[0..14])
		@favourites = request_data("/_list/sort_array_by_value/favourite_count?group=true&stale=update_after")['rows']
		@favourites_html = get_tweet_html(@favourites[0..14])
	end

	def raw_data
		@db = @connection
		@design_document = request_data("")
	end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_db, only: [:show]

  # GET /tweets
  # GET /tweets.json
  # def index
  #   @tweets = Tweet.all
  # end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @doc = request_data("/_view/by_tweet_id?&include_docs=true&limit=1&key=%22#{params[:id]}%22&stale=update_after")['rows'][0]['doc']
    @tweet = params[:id] == @doc['id_str'] ? @doc : @doc['retweeted_status']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include TwitterApiHelper
  before_action :set_db

  # GET /users/1
  # GET /users/1.json
  def show
    @retweets = request_data("/_list/sort_array_by_value/retweet_count?group=true&startkey=[%22#{params[:id]}%22]&endkey=[%22#{params[:id]}%22,%7B%7D]&stale=update_after")['rows']
		@retweets_html = get_tweet_html(@retweets[0..9])
    @user = find_user(params[:id])
  end

  def index
    @users = request_data("/_list/sort_by_value/mentions_count?group=true&group_level=2&stale=update_after")['rows']
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/twitter_api_helper.rb
module TwitterApiHelper

	def home_timeline
		$twitter.home_timeline[0..4]
	end

	def find_user(user_id)
		$twitter.user(user_id.to_i)
	end

	def get_tweet(tweet_id)
		$twitter.oembed(tweet_id)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hashtags/index.html.erb
<div class="page-header">
  <h1>Hashtags</h1>
</div>
<div class="row">
	<div class="table-responsive">
	  <table class="table table-striped table-bordered table-hover">
	    <thead>
	      <tr>
	        <th>Hashtag</th>
	        <th>Count</th>
	      </tr>
	    </thead>
	    <tbody>
	      <% @hashtags.each do |row| %>
	        <tr>
	          <td><%= link_to row['key'][0], hashtag_path(row['key'][0]) %></td>
	          <td align='right'><%= row['value'] %></td>
	        </tr>
	      <% end %>
	    </tbody>
	  </table>
	</div>
</div>

app/views/hashtags/show.html.erb
<div class="page-header">
  <h1>#<%= @hashtags[0]['key'][0] %></h1>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="col-md-12">
  		<div id="hashtag_sentiment_chart_total" style="width:100%; height:400px;" data-hashtag="<%= params[:id].to_str %>"></div>
      <div id="hashtag_sentiment_chart_percentage" style="width:100%; height:400px;" data-hashtag="<%= params[:id].to_str %>"></div>
  	</div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= msg %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
	<small>
	A <a href="http://www.msi.unimelb.edu.au/study/graduate/master-of-information-technology/distributed-computing/2-years/">Masters of Information Technology</a>
	 - <a href="https://handbook.unimelb.edu.au/view/2016/COMP90019">Distributed Computing project</a>
	 by <a href="http://www.lukejones.com.au/">Luke Jones</a>
	 of <a href="http://unimelb.edu.au">University of Melbourne</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", "http://www.lukejones.com.au" %></li>
      <li><%= link_to "Contact", "mailto:lukej1@unimelb.edu.au" %></li>
    </ul>
  </nav>
</div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "@ConversationTracker", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Hashtags", hashtags_path %></li>
        <li><%= link_to "Engagement", engagement_path %></li>
        <li><%= link_to "Sentiment Map", maps_path %></li>
        <li><%= link_to "Photos", photos_path %></li>
        <li><%= link_to "Raw Data", raw_data_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Tweet Analytics</title>

  <%= render "layouts/shim" %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script src="https://code.highcharts.com/modules/exporting.js"></script>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-51672834-4', 'auto');
    ga('send', 'pageview');

  </script>

  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <div class="container">
    <%= render "layouts/flash" %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/static_pages/dashboard.html.erb
<div class="page-header">
  <h1>Conversation Dashboard</h1>
</div>
<div class="row">
  <div class="col-md-12">
    <h1>Conversation overview</h1>
  </div>
	<div class="col-md-6">
    <div id="mentions_bar_chart" style="width:100%; height:400px;"></div>
	</div>
	<div class="col-md-6">
		<div id="hashtags_bar_chart" style="width:100%; height:400px;"></div>
	</div>
  <div class="col-md-12">
    <h1>Top words</h1>
    <div id="word_cloud" style="width:100%; height:400px;"></div>
  </div>
  <div class="col-md-12">
    <hr>
    <label for="stopwords">Stopwords for charts</label>
    <p>To remove a 'noisy' term, hashtag or user from the charts above just enter the term into the list below and click 'Update'</p>
    <textarea class="form-control" id="stopwords" name="stopwords"></textarea>
    <br>
    <button type="button" class="btn btn-primary" onclick="updateCharts()">Update</button>
    <br>
  </div>
</div>

app/views/static_pages/engagement.html.erb
<div class="page-header">
  <h1>Engagement and Influence</h1>
</div>
<div class="row">
  <div class="col-md-12">
    <h1>Retweet overview</h1>
    <div id="retweet_type_chart" style="width:100%; height:400px;"></div>
  </div>
  <div class="col-md-6">
    <h2>Most Retweeted</h2>
    <% @retweets_html.each do |row| %>
      <%= raw(row.html) %>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2>Most Favourited</h2>
    <% @favourites_html.each do |row| %>
      <%= raw(row.html) %>
    <% end %>
  </div>
</div>

app/views/static_pages/maps.html.erb
<script src="http://code.highcharts.com/maps/modules/map.js"></script>
<script src="http://code.highcharts.com/maps/modules/data.js"></script>
<script src="http://code.highcharts.com/mapdata/countries/us/us-all.js"></script>
<script src="http://code.highcharts.com/mapdata/custom/world.js"></script>
<!-- Flag sprites service provided by Martijn Lafeber, https://github.com/lafeber/world-flags-sprite/blob/master/LICENSE -->
<link rel="stylesheet" type="text/css" href="https://cloud.github.com/downloads/lafeber/world-flags-sprite/flags32.css" />

<div class="page-header">
  <h1>Sentiment by Country and US State</h1>
</div>
<div class="row">
  <div class="col-md-4">
    <h3>Description</h3>
    <p>These charts show the average sentiment score for each region.
      Each tweet has been tagged with a sentiment score ranging from:
      <ul>
        <li>-1 = negative sentiment
        <li>1 = positive sentiment
      </ul>
      Only tweets with a tagged location have been included. Therefore
      if a country/state is blank it indicate that no tweets with that
      country/state have been identified in the data set.
    </p>
  </div>
  <div class="col-md-8">
    <div id="country_sentiment_map" style="height: 500px; min-width: 310px; max-width: 100%; margin: 0 auto"></div>
    <div id="us_sentiment_map" style="height: 500px; min-width: 310px; max-width: 100%; margin: 0 auto"></div>
  </div>
</div>

app/views/static_pages/photos.html.erb
<div class="page-header">
  <h1>Photos</h1>
</div>
<div class="row">
  <div class="col-md-6">
    <h2>Most Popular Photos</h2>
    <% @photos.each do |row| %>
      <% count = "count="+ row["value"].to_s %>
      <a href=<%= row['key'] %>><img id='top_images' src=<%= row['key'] %> title=<%= count %>></a>
      <br>
    <% end %>
  </div>
</div>

app/views/static_pages/raw_data.html.erb
<div class="page-header">
  <h1>Raw data</h1>
</div>
<div class="row">
  <div class="col-md-12">
  This page contains a links to the raw data in the database. All data is in json format. To save a copy open the link, click save and save the page source.
  </div>
  <div class="col-md-4">
    <h2>Views</h2>
    <% [1,2,3,4,5,6,7,8,9].each do |level| %>
      <b>Group level <%= level %></b>
        <ul>
        <% @design_document["views"].each do |row| %>
          <% if !row[0].downcase.include? "count" %>
            <li><a href="<%= @connection + '/_view/'+ row[0] + '?group_level=' + level.to_s %>"><%= row[0] %></a></li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="col-md-4">
    <h2>Lists</h2>
    <h4>Sort by value</h4>
    <% [1,2,3,4,5,6,7,8,9].each do |level| %>
      <b>Group level <%= level %></b>
        <ul>
        <% @design_document["views"].each do |row| %>
          <% if row[0].downcase.include? "count" %>
            <li><a href="<%= @connection + '/_list/sort_by_value/'+ row[0] + '?group_level=' + level.to_s %>"><%= row[0] %></a></li>
            <% end %>
          <% end %>
      </ul>
    <% end %>
    <h4>Sort array by value</h4>
    <% [1,2,3,4,5,6,7,8,9].each do |level| %>
      <b>Group level <%= level %></b>
        <ul>
        <% @design_document["views"].each do |row| %>
          <% if row[0].downcase.include? "count" %>
            <li><a href="<%= @connection + '/_list/sort_array_by_value/'+ row[0] + '?group_level=' + level.to_s %>"><%= row[0] %></a></li>
            <% end %>
          <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="page-header">
  <h1>Tweet Details</h1>
</div>
<div class="row">
  <div class="col-md-12">
    <h3>Tweet</h3>
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Attribute</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><image src=<%= @tweet['user']['profile_image_url_https'] %>></td>
            <td><%= link_to @tweet['user']['name'], user_path(@tweet['user']['id_str']) %></td>
          </tr>
          <tr>
            <td>Text</td>
            <td><%= @tweet['text'] %></td>
          </tr>
          <tr>
            <td>Created At</td>
            <td><%= Time.parse(@tweet['created_at']).strftime('%H:%M on %d %b %Y') %></td>
          </tr>            
          <tr>
            <td>Favourite Count</td>
            <td><%= @tweet['favorite_count'] %></td>
          </tr>
          <tr>
            <td>Retweet Count</td>
            <td><%= @tweet['retweet_count'] %></td>
          </tr>      
        </tbody>
      </table>
    </div>
  </div>
</div>    

app/views/users/_user_profile.html.erb
<%= @user.description %><br><br>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Attribute</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Name</td>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <td>Verified Account</td>
        <td><%= @user.verified %></td>
      </tr>
      <tr>
        <td>Followers</td>
        <td><%= @user.followers_count %></td>
      </tr>
      <tr>
        <td>Statuses</td>
        <td><%= @user.statuses_count %></td>
      </tr>
      <tr>
        <td>Friends</td>
        <td><%= @user.friends_count %></td>
      </tr>
      <tr>
        <td>Location</td>
        <td><%= @user.location %></td>
      </tr>
      <tr>
        <td>Website</td>
        <td><%= @user.website %></td>
      </tr>
      <tr>
        <td>Account Created</td>
        <td><%= Time.parse(@user.created_at.to_s).in_time_zone(@user.utc_offset) %></td>
      </tr>
      <tr>
        <td>Time zone</td>
        <td><%= @user.time_zone %></td>
      </tr>
      <tr>
        <td>Language</td>
        <td><%= @user.lang %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<div class="page-header">
  <h1>Top Users</h1>
</div>
<div class="row">
	<div class="table-responsive">
	  <table class="table table-striped table-bordered table-hover">
	    <thead>
	      <tr>
	        <th>User</th>
	        <th>Count</th>
	      </tr>
	    </thead>
	    <tbody>
	      <% @users.each do |row| %>
	        <tr>
	          <td><%= link_to row['key'][1], user_path(row['key'][0]) %></td>
	          <td align='right'><%= row['value'] %></td>
	        </tr>
	      <% end %>
	    </tbody>
	  </table>
	</div>
</div>

app/views/users/show.html.erb
<div id="data" data-user="<%= params[:id].to_str %>"></div>
<div class="page-header">
  <h1><image src=<%= @user.profile_image_url %>> @<%= @user.screen_name %></h1>
</div>
<div class="row">
  <div class="col-md-4">
    <h2>Profile</h2>
    <%= render 'user_profile' %>
    <h2>Retweet contents</h2>
      <div id="retweet_type_chart" style="width:100%; height:400px;"></div>
      <p>This chart provides an overview as to the type of content contained in
        <%= @user.screen_name %>'s retweeted tweets.  Note that no minimum
        retweet count applies and a tweet can have more than one form of content
        , i.e. a photo and a link.</p>
    <h2>Most Retweeted</h2>
    <p><%= @user.screen_name %>'s most retweeted tweets are shown here.
      Note that only retweets that have been captured in the database and have
       > 10 retweets will be displayed.</p>
    <% @retweets_html.each do |row| %>
      <%= raw(row.html) %>
    <% end %>
  </div>
  <div class="col-md-8">
    <h2>Mentions of @<%= @user.screen_name %></h2>
    	<div id="mentions_sentiment_time_total_chart" style="width:100%; height:400px;"></div>
      <div id="mentions_sentiment_time_percentage_chart" style="width:100%; height:400px;"></div>
  </div>
  <div class="col-md-8">
    <h2>Tweets by @<%= @user.screen_name %></h2>
      <div id="tweets_sentiment_time_total_chart" style="width:100%; height:400px;"></div>
      <div id="tweets_sentiment_time_percentage_chart" style="width:100%; height:400px;"></div>
  </div>
  <div class="col-md-4">
  </div>
</div>